#!/usr/bin/env ruby

require 'chef/cookbook/metadata'

metadata_file = ARGV.first || 'metadata.rb'

# read in metadata
metadata = Chef::Cookbook::Metadata.new
metadata.from_file(metadata_file)

# output cookbook name and version
puts "#{metadata.version}"
